### Scoepe: Prratical Introduction to Recommendation system
<p>Building a simple collabroative filtering recommendation systen using the movielens dataset, implementing a basic content-based recommendation system using item features, Introduction to hybrid recommendataion system</p>
<p>Firstly it used emperical logic now due to deep learing this leap was introduced</p>

### Goal
<hr>
<p>By the end, we will be able to understand and implement basic recommendation systems using collaborative and contendt based filtering techniques<p>

### Overview of recommendation systems
<p>Recommendtaion systems are algorithms that sugesst revelent items to users based on their preferences. These systems are widely used in e-commerce, streming services, and social media platforms, The two main types of recommencation systems are:</p>
<ol>
    <li><b>Collaborative Filtering:</b> This method makes recommendations based on the preferences of similar users or items.</li>
    <li><b>Content-Based Filtering:</b> THis method recommends items similar to those the user has shown interest in, based on item features. Past history of the person and recommendation is given.</li>
</ol>

#### Collaborative Filtering Recommendation System
<p>We will build a simple collaborative filtering system using the movielens dataset. This data set contains user ratings for different movies, and we'll use it to recommend movies to users based on their past ratings</p>
<p>If the two user taste is similar then the taste of one user will be liked by other users as well. This is the collaborative way.</p>
<p>We will use cosine similarity that will look upon text and text and vecrotize text and distance between vector and identify the similiary and differecne in users.</p>

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# load the Movie lense data set
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.data'
columns = ['user_id', 'item_id', 'rating', 'timestamp'] #column for dataframe
df = pd.read_csv(url,sep = '\t', names = columns ) #reading dataframe from url seperate by'\t'
df.head(6)

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596
5      298      474       4  884182806

In [3]:
# create a user item matrix
user_item_matrix = df.pivot_table(index= 'user_id', columns='item_id', values='rating' )#structure change
user_item_matrix.fillna(0, inplace=True) # if N/a then place it with 0
user_item_matrix.head(6)
# data set structure change, now modified like truth table where rating is looked at with the item and user id where 0 is no rating a matrix of piviot table.
# previously we only looked at columns now both row and column to determine value 
# user id index or row, columns is the item id and see the value of rating on the basis or this

item_id  1     2     3     4     5     6     ...  1677  1678  1679  1680  1681  1682
user_id                                      ...
1         5.0   3.0   4.0   3.0   3.0   5.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2         4.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3         0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
4         0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
5         4.0   3.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
6         4.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0

[6 rows x 1682 columns]

In [4]:
# Calcualte the similarity between users
# the only AI here
user_similarity  = cosine_similarity(user_item_matrix)
# cosine on the basis of users, searches the similarity among user for all item and user ratings.
user_similarity_df = pd.DataFrame(user_similarity, index=user_item_matrix.index, columns=user_item_matrix.index) # keep the above index(row) and columns (above matrix)
user_similarity_df.head() # the data frame is in respect to user id and user id and the similarity in their rating 
# the matrix of all similarity score
# the user id 1 is similar to user id 1 100%; and so forth
# the user id 1 gave item id 1 rating of 5.0 and user id 2 gave 4.0. and the similarity differecne is 1point and checked in all cells of user id one and two 
# then on the basis of checking all the similarity among the user we gain a sense of taste of similarity with the user 1 and 2 after all item are checked between user id 1 and 2.
# done pair wise and puts the average value. Cosine similarity formula.


# predict the new user item rating check based on similar user rating what will the user rating could be

user_id       1         2         3    ...       941       942       943
user_id                                ...
1        1.000000  0.166931  0.047460  ...  0.148617  0.179508  0.398175
2        0.166931  1.000000  0.110591  ...  0.161485  0.172268  0.105798
3        0.047460  0.110591  1.000000  ...  0.101243  0.133416  0.026556
4        0.064358  0.178121  0.344151  ...  0.152041  0.170086  0.058752
5        0.378475  0.072979  0.021245  ...  0.139595  0.152497  0.313941

[5 rows x 943 columns]

In [5]:
# what we can do is check on the basis of user rating find similar user 
similar_users = user_similarity_df[1]
similar_users.sort_values(ascending=False).head(10)
#10 most similar user to user 1

user_id
1      1.000000
916    0.569066
864    0.547548
268    0.542077
92     0.540534
435    0.538665
457    0.538476
738    0.527031
429    0.525950
303    0.525718
Name: 1, dtype: float64

<p>Row and column of the whole matrx (user_item_matrix)</p>
<img src = 'row and column.png'>
<hr>
<p>Row of User 1 (user_similarity_df)</p>
<img src = 'row.png'>
<br/>
Dot product to identify the average rating a user might give to a movie

In [6]:
# predict ratings for unseen movies using collaborative filtering
# based on similar user like the given user what could be the rating of the items(movie) based on similar users.
def predict_ratings(user_id, user_item_matrix, user_similarity_df):
    similar_users = user_similarity_df[user_id] # select current user index and their values.
    weighted_ratings = np.dot(similar_users, user_item_matrix) # user 1 information is dot product with the user_item_matrix
    # similar users and user_id_matrix is multiplied, gives the average and gives a rough estimate of similarity. 
    # so user id 1 row the user id 1 and user id 2 are 0.16693 similar 
    # now dot product with the item 1 where user 2 gave 4.0 is multiplied with 0.16693 the user 2 on avg will give 0.66 rating to the item 1 this is the predicted value that user 1 will give due to their similarity
    # after this the weight are sum together to get an average value of the weight 
    # basically the item id row or the user 1(user_item_matrix) is multiplied with the row column of (user_similarity_df) to find item weights
    # predicted ratings average on the basis of similarity
    # the array given is the item rating sum 

    sum_of_weights = np.abs(similar_users).sum()
    predicted_ratings = weighted_ratings/sum_of_weights # finding out the average of all the user on all items 
    # each item of the rating array is divided by the sum of the similarity to get average array of the expected rating of the item
    return pd.Series(predicted_ratings, index=user_item_matrix.columns)

# exampel: predict ratings for a spefic user/ Sorting the rating to give an idea what item a user will like it 
user_id = 1 
predicted_ratings = predict_ratings(user_id, user_item_matrix, user_similarity_df)
predicted_ratings.sort_values(ascending = False).head(10) #decending order
#the user 1 will like Item 50 the most.
# found user similar to user id 1 and in case rating was given and on the basis of average gives the predcition of the ratings
# calculate trending a case in which a item is given high score by everyone

item_id
50     3.508250
181    2.858835
100    2.858604
174    2.827843
98     2.600223
56     2.507181
172    2.483425
127    2.449196
1      2.424921
173    2.187382
dtype: float64

#### Content-Based Recommendation system
<p>Next, we'll build a content based recommendation system. In this approch, we use the features of the items(eg, movie, generes, description) to recommend items similar to those the user has liked in the past.</p>
<p>Data frame of movies and generas; Only one user target, One youtuber, where title is looked generes covered, content based recomendation prefered, from past video posted we get the information of viral videos, and make recommendation on what videos might go viral. From collabroative filtering find similar youtuber cosine similarity and see what can be the status of other youtuber in the same video.</p>

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

# example data set: Movie titles and genres
movies = {
    'title' : ['Movie A', 'Movie B', 'Movie C', 'Movie D'],
    'genres': ['Action|Adventure', 'Adventure|Comedy', 'Comedy|Romance', 'Action|Thriller']
}
movies_df = pd.DataFrame(movies)
movies_df

     title            genres
0  Movie A  Action|Adventure
1  Movie B  Adventure|Comedy
2  Movie C    Comedy|Romance
3  Movie D   Action|Thriller

TFIDF identifies the genres in the corresponding data and then seperate the topics and find out the score. Similar to bag of words vectorization, similar to the bag of words every movie value are represented in a number.

In [22]:
# vectorize the geners using TF-Idf
tfidf = TfidfVectorizer(token_pattern='[a-zA-Z0-9_]+') 
tfidf_matrix = tfidf.fit_transform(movies_df['genres'])
#seperate the genres and see in the movie list how many time the genere are repeted covert to number form. on the basis of repeting give number value
tfidf_feature_names = tfidf.get_feature_names_out()
pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_feature_names, index = movies_df['title'])

           action  adventure    comedy   romance  thriller
title
Movie A  0.707107   0.707107  0.000000  0.000000  0.000000
Movie B  0.000000   0.707107  0.707107  0.000000  0.000000
Movie C  0.000000   0.000000  0.619130  0.785288  0.000000
Movie D  0.619130   0.000000  0.000000  0.000000  0.785288

In [23]:
# can also use croma db
cosine_sim = cosine_similarity(tfidf_matrix) #fit the matrix above with cosine similarity and see similar movies  
cosine_sim_df = pd.DataFrame(cosine_sim, index=movies_df['title'], columns=movies_df['title'])
cosine_sim_df #here movie a and movieb has a similar genere ie adventure and as such they are similar
# movie A and D are 0.43 similar

title     Movie A   Movie B   Movie C   Movie D
title
Movie A  1.000000  0.500000  0.000000  0.437791
Movie B  0.500000  1.000000  0.437791  0.000000
Movie C  0.000000  0.437791  1.000000  0.000000
Movie D  0.437791  0.000000  0.000000  1.000000

In [32]:
# recommend movies similar to a given movies
def recommend_movies(title, cosine_sim_df, num_recommendations = 3):
    similar_scores = cosine_sim_df[title]
    similar_movies = similar_scores.sort_values(ascending = False)[1:]
    return similar_movies

# example : recommed movies similar to movie a
recommendations = recommend_movies('Movie A', cosine_sim_df)
recommendations

title
Movie B    0.500000
Movie D    0.437791
Movie C    0.000000
Name: Movie A, dtype: float64